apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-prometheus-stack-kube-scheduler
  namespace: monitoring-system
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      component: kube-scheduler