---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
spec:
  destination:
    namespace: arr
    server: https://kubernetes.default.svc
  project: arr
  source:
    path: apps/arr/sonarr
    plugin:
      name: vault-kustomized-helm
    repoURL: https://github.com/Franjly/homelab-pi-k3s.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true