uptime-kuma:
  image:
    repository: louislam/uptime-kuma
    tag: 1.18.5-alpine

  env:
    TZ: Europe/Madrid
    UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN: 0

    ingress:
      main:
        enabled: true

        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-staging
          # kubernetes.io/tls-acme: "true"

        ingressClassName: "nginx"

        hosts:
          - host: uptime-kuma.local.tecno-fly.com
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: uptime-kuma
                  port: 3001
        tls:
        - secretName: uptime-kuma-tls
          hosts:
            - uptime-kuma.local.tecno-fly.com

  persistence:
    data:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      mountPath: /app/data