radarr:
  image:
    repository: ghcr.io/k8s-at-home/radarr
    tag:

  env:
    TZ: Europe/Madrid

  ingress:
    main:
      enabled: true
      primary: true

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        # kubernetes.io/tls-acme: "true"

      ingressClassName: "nginx"

      hosts:
        - host: radarr.local.tecno-fly.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: radarr
                port: 7878
      tls:
       - secretName: radarr-tls
         hosts:
           - radarr.local.tecno-fly.com

  # -- Configure persistence settings for the chart under this key.
  ## Config persistence is required for the Prometheus exporter sidecar.
  # @default -- See values.yaml
  persistence:
    config:
      enabled: false

    media:
      enabled: false
      mountPath: /media

  metrics:
    # -- Enable and configure Exportarr sidecar and Prometheus serviceMonitor.
    # @default -- See values.yaml
    enabled: false
    serviceMonitor:
      interval: 3m
      scrapeTimeout: 1m
      labels: {}
    # -- Enable and configure Prometheus Rules for the chart under this key.
    # @default -- See values.yaml
    prometheusRule:
      enabled: false
      labels: {}
      # -- Configure additionial rules for the chart under this key.
      # @default -- See prometheusrules.yaml
      rules: []
        # - alert: RadarrDown
        #   annotations:
        #     description: Radarr service is down.
        #     summary: Radarr is down.
        #   expr: |
        #     radarr_system_status == 0
        #   for: 5m
        #   labels:
        #     severity: critical
    exporter:
      image:
        # -- image repository
        repository: ghcr.io/onedr0p/exportarr
        # -- image tag
        tag: v1.0.0
        # -- image pull policy
        pullPolicy: IfNotPresent
      env:
        # -- metrics port
        port: 9793
        # -- Set to true to enable gathering of additional metrics (slow)
        additionalMetrics: false
        # -- Set to true to enable gathering unknown queue items
        unknownQueueItems: false