---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/service.name: calico-kube-controllers-metrics
  name: calico-kube-controllers
  namespace: calico-system
spec:
  endpoints:
  - interval: 30s
    port: metrics-port
  namespaceSelector:
    matchNames:
    - calico-system
  selector:
    matchLabels:
      app.kubernetes.io/service.name: calico-kube-controllers-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/service.name: felix-metrics-svc
  name: calico-felix
  namespace: calico-system
spec:
  endpoints:
  - interval: 30s
    port: metrics-port
  namespaceSelector:
    matchNames:
    - calico-system
  selector:
    matchLabels:
      app.kubernetes.io/service.name: felix-metrics-svc
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/service.name: typha-metrics-svc
    app.kubernetes.io/pod.container.port.name: calico-typha
  name: calico-typha
  namespace: calico-system
spec:
  endpoints:
  - interval: 30s
    port: metrics-port
  namespaceSelector:
    matchNames:
    - calico-system
  selector:
    matchLabels:
      app.kubernetes.io/service.name: typha-metrics-svc
      app.kubernetes.io/pod.container.port.name: calico-typha
