---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: calico-kube-controllers
  name: calico-kube-controllers
  namespace: calico-system
spec:
  endpoints:
  - interval: 30s
    port: metrics-port
  namespaceSelector:
    matchNames:
    - calico-system
  selector:
    matchLabels:
      k8s-app: calico-kube-controllers
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: calico-node
  name: calico-felix
  namespace: calico-system
spec:
  endpoints:
  - interval: 30s
    port: metrics-port
  namespaceSelector:
    matchNames:
    - calico-system
  selector:
    matchLabels:
      k8s-app: calico-node
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: calico-typha
  name: calico-typha
  namespace: calico-system
spec:
  endpoints:
  - interval: 30s
    port: metrics-port
  namespaceSelector:
    matchNames:
    - calico-system
  selector:
    matchLabels:
      k8s-app: calico-typha
