apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: calico-typha
  name: typha-metrics-svc
  namespace: calico-system
spec:
  clusterIP: None
  selector:
    k8s-app: calico-typha
  ports:
  - name: metrics-port
    port: 9093
    targetPort: 9093