calibre-web:
  image:
    repository: linuxserver/calibre-web
    tag: version-0.6.12

  env:
    TZ: Europe/Madrid

  ingress:
    main:
      enabled: true

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        # kubernetes.io/tls-acme: "true"

      ingressClassName: "nginx"

      hosts:
        - host: calibre-web.local.tecno-fly.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: calibre-web
                port: 8083
      tls:
       - secretName: calibre-web-tls
         hosts:
           - calibre-web.local.tecno-fly.com

  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    config:
      enabled: true
      storageClass: longhorn
      mountPath: /config

    media:
      enabled: true
      storageClass: nfs-media
      accessMode: ReadWriteOnce
      size: 6Ti
      mountPath: /media

    # books:
    #   enabled: false
    #   mountPath: /books