calibre-web:
  image:
    repository: linuxserver/calibre-web
    tag: 0.6.19-ls183

  env:
    TZ: Europe/Madrid

  ingress:
    main:
      enabled: true

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        # kubernetes.io/tls-acme: "true"
        hajimari.io/appName: Calibre - Web
        hajimari.io/icon: book-open-page-variant
        hajimari.io/group: Media
        hajimari.io/targetBlank: 'false'

      ingressClassName: "nginx"

      hosts:
        - host: calibre-web.local.tecno-fly.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: calibre-web
                port: 8083
      tls:
       - secretName: calibre-web-tls
         hosts:
           - calibre-web.local.tecno-fly.com

  persistence:
    config:
      enabled: true
      storageClass: longhorn
      mountPath: /config

    media:
      enabled: true
      storageClass: nfs-media
      accessMode: ReadWriteOnce
      size: 6Ti
      mountPath: /media