hajimari:
  hajimari:
    # -- The name of this instance, this allows running multiple 
    # instances of Hajimari on the same cluster
    instanceName: null

    # -- Set to true to show all discovered applications by default.
    defaultEnable: true

    # -- Namespace selector to use for discovering applications
    namespaceSelector:
      any: true
      
    # -- Override the title of the Hajimari pages
    title: null

    lightTheme: tron
    darkTheme: tron

    # -- Default name for welcome message
    name: "FLY"

    # -- Add custom applications to the discovered application list
    customApps: []
    # - group: Media
    #   apps:
    #     - name: Test
    #       url: 'https://example.com'
    #       icon: 'mdi:test-tube'
    #       info: This is a test app
    
    # -- Set default bookmarks
    bookmarks: []
    # - group: Communicate
    #   bookmarks:
    #   - name: Discord
    #     url: 'https://discord.com'
    #   - name: Gmail
    #     url: 'http://gmail.com'
    #   - name: Slack
    #     url: 'https://slack.com/signin'

  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        hajimari.io/enable: 'false'
      hosts:
        - host: home.local.tecno-fly.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: hajimari-tls
          hosts:
            - home.local.tecno-fly.com

  persistence:
    data:
      enabled: false
      storageClass: longhorn
  
  initContainers: {}