namespace: monitoring-system

resources:
- ./resources/alertmanager-discord.yaml
- ./resources/all.yaml

patches:
- ./patches/crd-prometheuses.yaml
- ./patches/kube-prometheus-stack-kube-proxy-service-monitor.yaml
- ./patches/kube-prometheus-stack-kube-controller-manager-service-monitor.yaml
- ./patches/kube-prometheus-stack-kube-scheduler-service-monitor.yaml
# - ./patches/kube-prometheus-stack-kube-scheduler-svc.yaml
# - ./patches/kube-prometheus-stack-kube-controller-manager-svc.yaml

patchesJson6902:
- target:
    group: core
    version: v1 
    kind: Service
    name: kube-prometheus-stack-kube-controller-manager
    namespace: monitoring-system
  patch: |
    - op: add
      path: /metadata/labels/component1
      value: kube-controller-manager1