namespace: monitoring-system

resources:
- ./resources/alertmanager-discord.yaml
- ./resources/all.yaml

patches:
- ./patches/crd-prometheuses.yaml
- ./patches/kube-prometheus-stack-kube-proxy-service-monitor.yaml
- ./patches/kube-prometheus-stack-kube-controller-manager-service-monitor.yaml
- ./patches/kube-prometheus-stack-kube-scheduler-service-monitor.yaml
# - ./patches/kube-prometheus-stack-kube-scheduler-svc.yaml
# - ./patches/kube-prometheus-stack-kube-controller-manager-svc.yaml

# kubectl label svc kube-prometheus-stack-kube-controller-manager -n monitoring-system prueba=true

transformers:
- ./transformers/kube-prometheus-stack-kube-controller-manager-svc.yaml