namespace: monitoring-system

resources:
- ./resources/alertmanager-discord.yaml
- ./resources/all.yaml

patches:
- ./patches/crd-prometheuses.yaml
- ./patches/kube-prometheus-stack-kube-proxy-service-monitor.yaml
