kube-prometheus-stack:
  ## Create default rules for monitoring the cluster
  ##
  defaultRules:
    create: true
    rules:
      alertmanager: true
      etcd: true
      configReloaders: true
      general: true
      k8s: true
      kubeApiserverAvailability: true
      kubeApiserverBurnrate: true
      kubeApiserverHistogram: true
      kubeApiserverSlos: true
      kubeControllerManager: true
      kubelet: true
      kubeProxy: true
      kubePrometheusGeneral: true
      kubePrometheusNodeRecording: true
      kubernetesApps: true
      kubernetesResources: true
      kubernetesStorage: true
      kubernetesSystem: true
      kubeScheduler: true
      kubeStateMetrics: true
      network: true
      node: true
      nodeExporterAlerting: true
      nodeExporterRecording: true
      prometheus: true
      prometheusOperator: true

  ## Configuration for alertmanager
  ## ref: https://prometheus.io/docs/alerting/alertmanager/
  ##
  alertmanager:
    enabled: true

    config:
      global:
        resolve_timeout: 5m
      inhibit_rules:
        - source_matchers:
            - 'severity = critical'
          target_matchers:
            - 'severity =~ warning|info'
          equal:
            - 'namespace'
            - 'alertname'
        - source_matchers:
            - 'severity = warning'
          target_matchers:
            - 'severity = info'
          equal:
            - 'namespace'
            - 'alertname'
        - source_matchers:
            - 'alertname = InfoInhibitor'
          target_matchers:
            - 'severity = info'
          equal:
            - 'namespace'
      route:
        group_by: ['namespace']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: 'discord_webhook'
        routes:
        - receiver: 'null'
          matchers:
            - alertname =~ "InfoInhibitor|Watchdog"
      receivers:
      - name: 'null'
      - name: 'discord_webhook'
        webhook_configs:
        - url: 'http://alertmanager-discord.monitoring-system.svc.cluster.local:9094'
      templates:
      - '/etc/alertmanager/config/*.tmpl'

    ingress:
      enabled: true

      ingressClassName: nginx

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        # kubernetes.io/tls-acme: "true"
        # hajimari.io/appName: AlertManager
        # hajimari.io/icon: chart-bar
      hosts:
        - alertmanager.local.tecno-fly.com
      paths:
        - /
      tls: 
        - secretName: alertmanager-tls
          hosts:
          - alertmanager.local.tecno-fly.com
    
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn
            resources:
              requests:
                storage: 25Gi

  grafana:
    enabled: true

    defaultDashboardsTimezone: Europe/Madrid

    adminUser: <path:pi-k3s/data/system/monitoring-system/grafana#admin-user>
    adminPassword: <path:pi-k3s/data/system/monitoring-system/grafana#admin-passwd>

    ingress:
      enabled: true

      ingressClassName: nginx

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        # kubernetes.io/tls-acme: "true"
        # hajimari.io/appName: Grafana
        # hajimari.io/icon: chart-bar
      hosts:
        - grafana.local.tecno-fly.com
      path: /
      tls:
        - secretName: grafana-tls
          hosts:
          - grafana.local.tecno-fly.com

    persistence:
      enabled: false
      storageClassName: longhorn
      size: 10Gi

    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        folder: /tmp/dashboards

        ## Annotations for Grafana dashboard configmaps
        ##
        annotations:
          k8s-sidecar-target-directory: /tmp/dashboards/kubernetes

        multicluster:
          global:
            enabled: false
          etcd:
            enabled: false
        provider:
          allowUiUpdates: false
          foldersFromFilesStructure: true
          
      datasources:
        enabled: true
        defaultDatasourceEnabled: true

        uid: prometheus

        ## URL of prometheus datasource
        ##
        # url: http://prometheus-stack-prometheus:9090/

        # If not defined, will use prometheus.prometheusSpec.scrapeInterval or its default
        # defaultDatasourceScrapeInterval: 15s

        ## Annotations for Grafana datasource configmaps
        ##
        annotations: {}

        ## Create datasource for each Pod of Prometheus StatefulSet;
        ## this uses headless service `prometheus-operated` which is
        ## created by Prometheus Operator
        ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/0fee93e12dc7c2ea1218f19ae25ec6b893460590/pkg/prometheus/statefulset.go#L255-L286
        createPrometheusReplicasDatasources: false
        label: grafana_datasource
        labelValue: "1"

        ## Field with internal link pointing to existing data source in Grafana.
        ## Can be provisioned via additionalDataSources
        exemplarTraceIdDestinations: {}
          # datasourceUid: Jaeger
          # traceIdLabelName: trace_id

    plugins:
      - grafana-piechart-panel

    extraConfigmapMounts: []
    # - name: certs-configmap
    #   mountPath: /etc/grafana/ssl/
    #   configMap: certs-configmap
    #   readOnly: true

    deleteDatasources: []
    # - name: example-datasource
    #   orgId: 1

    ## Configure additional grafana datasources (passed through tpl)
    ## ref: http://docs.grafana.org/administration/provisioning/#datasources
    additionalDataSources:
      - name: Loki
        type: loki
        uid: loki
        url: http://loki.monitoring-system:3100
        isDefault: false

    # envFromSecret: grafana-secrets

    ## Configure grafana dashboard providers
    ## ref: http://docs.grafana.org/administration/provisioning/#dashboards
    ##
    ## `path` must be /var/lib/grafana/dashboards/<provider_name>
    ##
    dashboardProviders: 
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'loki'
          orgId: 1
          folder: 'Loki'
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/loki

    ## Configure grafana dashboard to import
    ## NOTE: To use dashboards you must also enable/configure dashboardProviders
    ## ref: https://grafana.com/dashboards
    ##
    ## dashboards per provider, use provider name as key.
    ##
    dashboards:
      loki:
        loki-dashboard:
          json: |
            {"annotations":{"list":[{"$$hashKey":"object:75","builtIn":1,"datasource":"-- Grafana --","enable":true,"hide":true,"iconColor":"rgba(0, 211, 255, 1)","name":"Annotations & Alerts","target":{"limit":100,"matchAny":false,"tags":[],"type":"dashboard"},"type":"dashboard"}]},"description":"Loki logs panel with prometheus variables ","editable":true,"fiscalYearStartMonth":0,"gnetId":12019,"graphTooltip":0,"iteration":1644880408496,"links":[],"liveNow":false,"panels":[{"aliasColors":{},"bars":true,"dashLength":10,"dashes":false,"datasource":{"type":"loki","uid":"loki"},"fieldConfig":{"defaults":{"links":[]},"overrides":[]},"fill":1,"fillGradient":0,"gridPos":{"h":3,"w":24,"x":0,"y":0},"hiddenSeries":false,"id":6,"legend":{"avg":false,"current":false,"max":false,"min":false,"show":false,"total":false,"values":false},"lines":false,"linewidth":1,"nullPointMode":"null","options":{"alertThreshold":true},"percentage":false,"pluginVersion":"8.3.5","pointradius":2,"points":false,"renderer":"flot","seriesOverrides":[],"spaceLength":10,"stack":false,"steppedLine":false,"targets":[{"expr":"sum(count_over_time({namespace=\"$namespace\", pod=~\"$pod\"} |~ \"$search\"[$__interval]))","refId":"A"}],"thresholds":[],"timeRegions":[],"tooltip":{"shared":true,"sort":0,"value_type":"individual"},"type":"graph","xaxis":{"mode":"time","show":true,"values":[]},"yaxes":[{"$$hashKey":"object:168","format":"short","logBase":1,"show":false},{"$$hashKey":"object:169","format":"short","logBase":1,"show":false}],"yaxis":{"align":false}},{"datasource":{"type":"loki","uid":"loki"},"gridPos":{"h":28,"w":24,"x":0,"y":3},"id":2,"maxDataPoints":"","options":{"dedupStrategy":"none","enableLogDetails":true,"prettifyLogMessage":false,"showCommonLabels":false,"showLabels":false,"showTime":true,"sortOrder":"Descending","wrapLogMessage":true},"targets":[{"expr":"{namespace=\"$namespace\", pod=~\"$pod\"} |~ \"$search\"","refId":"A"}],"title":"Logs Panel","type":"logs"}],"schemaVersion":34,"style":"dark","tags":[],"templating":{"list":[{"current":{"selected":true,"text":"monitoring","value":"monitoring"},"datasource":{"type":"prometheus","uid":"prometheus"},"definition":"label_values(kube_pod_info, namespace)","hide":0,"includeAll":false,"multi":false,"name":"namespace","options":[],"query":{"query":"label_values(kube_pod_info, namespace)","refId":"Prometheus-namespace-Variable-Query"},"refresh":1,"regex":"","skipUrlSync":false,"sort":0,"tagValuesQuery":"","tagsQuery":"","type":"query","useTags":false},{"allValue":".*","current":{"selected":true,"text":["All"],"value":["$__all"]},"datasource":{"type":"prometheus","uid":"prometheus"},"definition":"label_values(container_network_receive_bytes_total{namespace=~\"$namespace\"},pod)","hide":0,"includeAll":true,"multi":true,"name":"pod","options":[],"query":{"query":"label_values(container_network_receive_bytes_total{namespace=~\"$namespace\"},pod)","refId":"Prometheus-pod-Variable-Query"},"refresh":1,"regex":"","skipUrlSync":false,"sort":0,"tagValuesQuery":"","tagsQuery":"","type":"query","useTags":false},{"current":{"selected":false,"text":"","value":""},"hide":0,"name":"search","options":[{"selected":true,"text":"","value":""}],"query":"","skipUrlSync":false,"type":"textbox"}]},"time":{"from":"now-30m","to":"now"},"timepicker":{"refresh_intervals":["5s","10s","30s","1m","5m","15m","30m","1h","2h","1d"]},"timezone":"","title":"Loki Dashboard","uid":"liz0yRCZzwer","version":1,"weekStart":""}
        # custom-dashboard:
        #   file: dashboards/custom-dashboard.json
        # prometheus-stats:
        #   gnetId: 2
        #   revision: 2
        #   datasource: Prometheus
        # local-dashboard:
        #   url: https://example.com/repository/test.json
        #   token: ''
        # local-dashboard-base64:
        #   url: https://example.com/repository/test-b64.json
        #   token: ''
        #   b64content: true
        # local-dashboard-gitlab:
        #   url: https://example.com/repository/test-gitlab.json
        #   gitlabToken: ''
        # local-dashboard-bitbucket:
        #   url: https://example.com/repository/test-bitbucket.json
        #   bearerToken: ''

    grafana.ini:
      server:
        root_url: https://grafana.local.tecno-fly.com
      # auth.generic_oauth:
      #   enabled: true
      #   allow_sign_up: true
      #   name: Dex
      #   client_id: grafana-sso
      #   client_secret: $__env{GRAFANA_SSO_CLIENT_SECRET}
      #   scopes: openid profile email groups
      #   auth_url: https://dex.khuedoan.com/auth
      #   token_url: https://dex.khuedoan.com/token
      #   api_url: https://dex.khuedoan.com/userinfo

  prometheus:
    enabled: true

    ingress:
      enabled: true

      ingressClassName: nginx

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        # kubernetes.io/tls-acme: "true"
        # hajimari.io/appName: Prometheus
        # hajimari.io/icon: chart-bar
      hosts:
        - prometheus.local.tecno-fly.com
      paths:
        - /
      tls: 
        - secretName: prometheus-tls
          hosts:
            - prometheus.local.tecno-fly.com

    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn
            resources:
              requests:
                storage: 25Gi
