---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-vault-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
      namespace: argocd
    spec:
      init:
        command: [sh]
        args: [-c, 'echo "Initializing..."']
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
      discover:
        find:
          command: [sh, -c, find . -name kustomization.yaml] 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kustomized-helm
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kustomized-helm
      namespace: argocd
    spec:
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: [sh, -c]
        args: ["helm template $ARGOCD_APP_NAME --include-crds --api-versions monitoring.coreos.com/v1 --namespace $ARGOCD_APP_NAMESPACE . > resources/all.yaml && kustomize build"]
      discover:
        find:
          command: [sh, -c, find . -name kustomization.yaml] 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-kustomized-helm
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: vault-kustomized-helm
      namespace: argocd
    spec:
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: [sh, -c]
        args: ["helm template $ARGOCD_APP_NAME --include-crds --api-versions monitoring.coreos.com/v1 --namespace $ARGOCD_APP_NAMESPACE . > resources/all.yaml && kustomize build | argocd-vault-plugin generate -"]
      discover:
        find:
          command: [sh, -c, find . -name kustomization.yaml] 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-kustomized
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: vault-kustomized
      namespace: argocd
    spec:
      init:
        command: [sh]
        args: [-c, 'echo "Initializing..."']
      generate:
        command: [sh, -c]
        args: ["kustomize build | argocd-vault-plugin generate -"]
      discover:
        find:
          command: [sh, -c, find . -name kustomization.yaml] 
