namespace: longhorn-system

resources:
- ./secrets/longhorn-backup-target-credential-secret.yaml
- ./resources/all.yaml
- ./configs/longhorn-recurring-job.yaml

patchesStrategicMerge:
- ./patches/local-path.yaml
