namespace: longhorn-system

resources:
- ./secrets/longhorn-backup-target-credential-secret.yaml
- ./resources/all.yaml
- ./configs/longhorn-recurring-job.yaml
#- ./resources/service-monitor.yaml
#- ./resources/prometheus-rules.yaml

patches:
#- ./patches/local-path.yaml
