namespace: longhorn-system

resources:
- ./secrets/longhorn-backup-target-credential-secret.yaml
- ./resources/all.yaml
- ./configs/longhorn-recurring-job.yaml
- ./resources/service-monitor.yaml

patches:
- ./patches/longhorn-backend-svc.yaml
#- ./patches/local-path.yaml
