longhorn:
  persistence:
    defaultClassReplicaCount: 3
    reclaimPolicy: Retain
    recurringJobSelector:
      enable: true
      jobList: '[{"name":"snapshot-default","task":"snapshot","cron":"0 5 * * *","retain":3},{"name":"backup-default","task":"backup","cron":"0 6 * * *","retain":3}]'

  defaultSettings:
    backupTarget: s3://longhorn-backups@us-east-1/
    backupTargetCredentialSecret: longhorn-backup-target-credential-secret
    defaultDataPath: /data/longhorn
    taintToleration: node-role.kubernetes.io/master=true:NoSchedule
    defaultLonghornStaticStorageClass: longhorn

  longhornManager:
    tolerations:
    - key: node-role.kubernetes.io/master
      operator: Equal
      value: "true"
      effect: NoSchedule

  # longhornDriver:
  #   tolerations:
  #   - key: node-role.kubernetes.io/master
  #     operator: Equal
  #     value: "true"
  #     effect: NoSchedule

  # longhornUI:
  #   tolerations:
  #   - key: node-role.kubernetes.io/master
  #     operator: Equal
  #     value: "true"
  #     effect: NoSchedule 

  ingress:
    enabled: true
    ingressClassName: nginx
    host: longhorn.local.tecno-fly.com
    tls: true
    secureBackends: true
    tlsSecret: longhorn-tls

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
      # kubernetes.io/tls-acme: true

  enablePSP: false
