longhorn:
  persistence:
    defaultClassReplicaCount: 2
    reclaimPolicy: Retain
    recurringJobSelector:
      enable: true
      jobList: '[{"name":"snapshot-default","task":"snapshot","cron":"0 5 * * *","retain":3},{"name":"backup-default","task":"backup","cron":"0 6 * * *","retain":3}]'

  defaultSettings:
    backupTarget: s3://longhorn-backups@us-east-1/
    backupTargetCredentialSecret: longhorn-backup-target-credential-secret
    defaultDataPath: /data/longhorn

  ingress:
    enabled: true
    ingressClassName: nginx
    host: longhorn.local.tecno-fly.com
    tls: true
    secureBackends: true
    tlsSecret: longhorn-tls

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
      # kubernetes.io/tls-acme: true
