romm:
  image:
    repository: ghcr.io/rommapp/romm
    tag: 3.5@sha256:d3a0cd1d84a3f85f56d4995a2a29f3efd664e2d040bb09fa00be1aded4349ac4

  podOptions:
    nodeSelector:
      kubernetes.io/arch: null
  
  service:
    main:
      ports:
        main:
          protocol: http
          targetPort: 8080
          port: 10680

  ingress:
    main:
      enabled: true

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        # kubernetes.io/tls-acme: "true"

      ingressClassName: "nginx"

      hosts:
        - host: romm.local.tecno-fly.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: romm
                port: 10680
      tls:
        - secretName: romm-tls
          hosts:
            - romm.local.tecno-fly.com
      integrations:
        traefik:
          enabled: false

  romm:
    auth:
      user: <path:pi-k3s/data/apps/romm#user>
      pass: <path:pi-k3s/data/apps/romm#pass>

  workload:
    main:
      podSpec:
        containers:
          main:
            probes:
              liveness:
                type: http
              readiness:
                type: http
              startup:
                type: http
            env:
              ROMM_BASE_PATH: /romm
              ROMM_DB_DRIVER: mariadb
              CLIENT_ID: <path:pi-k3s/data/apps/romm#igdb-clientId>
              CLIENT_SECRET: <path:pi-k3s/data/apps/romm#igdb-clientSecret>
              STEAMGRIDDB_API_KEY: <path:pi-k3s/data/apps/romm#steamgriddb-apikey>
              DB_PORT: 3306
              DB_NAME: "{{ .Values.mariadb.mariadbDatabase }}"
              DB_USER: "{{ .Values.mariadb.mariadbUsername }}"
              DB_HOST:
                secretKeyRef:
                  expandObjectName: false
                  name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                  key: plainhost
              DB_PASSWD: "{{ .Values.mariadb.password }}"
              REDIS_HOST:
                secretKeyRef:
                  expandObjectName: false
                  name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                  key: plainhost
              REDIS_PASSWORD: "{{ .Values.redis.password }}"
              REDIS_PORT: 6379
              ROMM_AUTH_SECRET_KEY:
                secretKeyRef:
                  name: romm-secrets
                  key: ROMM_AUTH_SECRET_KEY
              ROMM_AUTH_ENABLED: true
              ENABLE_EXPERIMENTAL_REDIS: true
              ROMM_AUTH_USERNAME: "{{ .Values.romm.auth.user}}"
              ROMM_AUTH_PASSWORD: "{{ .Values.romm.auth.pass}}"

  persistence:
    library:
      enabled: true
      storageClass: nfs-roms
      size: 2Ti
      mountPath: /romm/library
    resources:
      enabled: true
      storageClass: nfs-roms
      size: 2Ti
      mountPath: /romm/resources
    config:
      enabled: true
      storageClass: longhorn
      size: 5Gi
      mountPath: /romm/config
    assets:
      enabled: true
      storageClass: nfs-roms
      size: 2Ti
      mountPath: /romm/assets

  mariadb:
    enabled: true
    includeCommon: true
    mariadbUsername: <path:pi-k3s/data/apps/romm#mariadbUsername>
    mariadbDatabase: romm

    podOptions:
      nodeSelector:
        kubernetes.io/arch: null

    persistence:
      data:
        enabled: true
        storageClass: longhorn
        size: 5Gi
        mountPath: "/bitnami/mariadb"

  redis:
    enabled: true
    includeCommon: true

    podOptions:
      nodeSelector:
        kubernetes.io/arch: null

  portal:
    open:
      enabled: true