tigera-operator:
  imagePullSecrets: {}

  installation:
    enabled: true
    calicoNetwork:
      bgp: Enabled
      ipPools:
        - cidr: 10.42.0.0/16
          blockSize: 26
          name: default-ipv4-ippool
          disableBGPExport: false
          encapsulation: VXLANCrossSubnet
          natOutgoing: Enabled
          nodeSelector: all()
          allowedUses:	
            - Workload	
            - Tunnel
        # - cidr: 10.43.0.0/16
        #   natOutgoing: Enabled
        #   nodeSelector: all()
      containerIPForwarding: Enabled
      linuxDataplane: Iptables
      multiInterfaceMode: None
      nodeAddressAutodetectionV4:
        # firstFound: true
        # interface: eth0
        cidrs:
        - "192.168.30.0/24"
        - "192.168.40.0/24"
        - "192.168.60.0/24"
    typhaMetricsPort: 9093

  apiServer:
    enabled: true

  certs:
    node:
      key:
      cert:
      commonName:
    typha:
      key:
      cert:
      commonName:
      caBundle:

  # Resource requests and limits for the tigera/operator pod.
  resources: {}

  # Tolerations for the tigera/operator pod.
  tolerations:
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists

  # NodeSelector for the tigera/operator pod.
  nodeSelector:
    kubernetes.io/os: linux

  # Custom annotations for the tigera/operator pod.
  podAnnotations: {}

  # Custom labels for the tigera/operator pod.
  podLabels: {}

  # Image and registry configuration for the tigera/operator pod.
  tigeraOperator:
    image: tigera/operator
    version: release-v1.35
    registry: quay.io
  calicoctl:
    image: docker.io/calico/ctl
    tag: release-v3.28
