unifi-poller:
  image:
    repository: golift/unifi-poller
    pullPolicy: IfNotPresent
    tag: v2.9.5


  # -- Environment variable configuration options for unifi-poller ([docs](https://unifipoller.com/docs/install/configuration)).
  #    Note: a [configuration file](https://github.com/unifi-poller/unifi-poller/blob/master/examples/up.conf.example) is also supported.
  # env:
  #   UP_UNIFI_DEFAULT_URL: "https://192.168.0.1"
  #   UP_UNIFI_DEFAULT_USER: <path:pi-k3s/data/system/monitoring-system/unifi-poller#UP_UNIFI_DEFAULT_USER>
  #   UP_UNIFI_DEFAULT_PASS: <path:pi-k3s/data/system/monitoring-system/unifi-poller#UP_UNIFI_DEFAULT_PASS>
  #   # UP_WEBSERVER_ENABLE: true
  #   UP_INFLUXDB_DISABLE: true
  #   UP_UNIFI_DEFAULT_SAVE_DPI: true
  #   UP_UNIFI_DEFAULT_SAVE_SITES: true
  #   # UP_LOKI_URL: http://loki.monitoring-system:3100
  #   UP_UNIFI_DEFAULT_SAVE_IDS: true
  #   UP_UNIFI_DEFAULT_SAVE_EVENTS: true
  #   UP_UNIFI_DEFAULT_SAVE_ALARMS: true
  #   UP_UNIFI_DEFAULT_SAVE_ANOMALIES: true
  #   # UP_PROMETHEUS_DISABLE: true

  service:
    main:
      ports:
        # http:
        #   enabled: true
        #   protocol: TCP
        #   port: 37288
        metrics:
          enabled: true
          protocol: TCP
          port: 9130

  ingress:
    main:
      enabled: true

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        # kubernetes.io/tls-acme: "true"
        hajimari.io/appName: UniFi-Poller
        hajimari.io/icon: chart-bell-curve-cumulative
        hajimari.io/group: Monitoring
        hajimari.io/targetBlank: 'false'

      ingressClassName: "nginx"

      hosts:
        - host: unifi-poller.local.tecno-fly.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: unifi-poller
                port: 37288
      tls:
        - secretName: unifi-poller-tls
          hosts:
            - unifi-poller.local.tecno-fly.com

  persistence:
    config:
      enabled: true
      type: secret
      name: unifi-poller-config
      mountPath: /etc/unpoller/up.conf
      subPath: unifi-poller.conf

  metrics:
    enabled: true
    serviceMonitor:
      interval: 1m
      scrapeTimeout: 30s
    prometheusRule:
      enabled: true
      rules:
        - alert: UnifiPollerAbsent
          annotations:
            description: Unifi Poller has disappeared from Prometheus service discovery.
            summary: Unifi Poller is down.
          expr: |
            absent(up{job=~".*unifi-poller.*"} == 1)
          for: 5m
          labels:
            severity: critical
