---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pod-info
spec:
  rules:
  - host: pod-info.local.tecno-fly.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pod-info
            port:
              number: 80
