readarr:
  image:
    repository: hotio/readarr
    tag: testing-0.1.1.1320

  env:
    TZ: Europe/Madrid

  ingress:
    main:
      enabled: true

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        # kubernetes.io/tls-acme: "true"
        hajimari.io/appName: Readarr
        hajimari.io/icon: book-open-blank-variant
        hajimari.io/group: Downloads
        hajimari.io/targetBlank: 'false'

      ingressClassName: "nginx"

      hosts:
        - host: readarr.local.tecno-fly.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: readarr
                port: 8787
      tls:
       - secretName: readarr-tls
         hosts:
           - readarr.local.tecno-fly.com

  persistence:
    config:
      enabled: true
      storageClass: longhorn
      size: 5Gi

    downloads:
      enabled: true
      storageClass: nfs-downloads
      accessMode: ReadWriteOnce
      size: 2Ti
      mountPath: /downloads

    media:
      enabled: true
      storageClass: nfs-media
      accessMode: ReadWriteOnce
      size: 6Ti
      mountPath: /media
