trivy:
  persistence:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 5Gi

  trivy:
    skipUpdate: false
    gitHubToken: <path:pi-k3s/data/platform/trivy-system#gitHubToken>
    serverToken: <path:pi-k3s/data/platform/trivy-system#serverToken>

  ingress:
    enabled: false
    ingressClassName: nginx

    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
      # kubernetes.io/tls-acme: "true"
      hajimari.io/appName: Trivy
      hajimari.io/icon: skull-scan
      hajimari.io/group: Platform
      hajimari.io/targetBlank: 'false'

    hosts:
      - host: trivy.local.tecno-fly.com
    path: "/"
    pathType: Prefix

    tls:
     - secretName: trivy-tls
       hosts:
         - trivy.local.tecno-fly.com
