apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared
  name: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:2023.8.2
        imagePullPolicy: IfNotPresent
        args: ["tunnel", "--no-autoupdate", "run", "--token=<path:pi-k3s/data/system/cloudflare/tunnel#token>"]
      restartPolicy: Always
      terminationGracePeriodSeconds: 60


# http://jellyfin-external-service.external-endpoints.svc.cluster.local:8096
