apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared
  name: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:2024.8.3
        imagePullPolicy: IfNotPresent
        args: ["tunnel", "--no-autoupdate", "run", "--token=<path:pi-k3s/data/system/cloudflare/tunnel#token>"]
        env:
        - name: TZ
          value: "Europe/Madrid"
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
