---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: monitoring-system
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://gitea.192.168.40.200.nip.io/homelab/pi-k3s.git
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8up
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: k8up
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://gitea.192.168.40.200.nip.io/homelab/pi-k3s.git
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: velero
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: velero
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://gitea.192.168.40.200.nip.io/homelab/pi-k3s.git
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: metallb-system
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: metallb-system
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://gitea.192.168.40.200.nip.io/homelab/pi-k3s.git
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://gitea.192.168.40.200.nip.io/homelab/pi-k3s.git
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: longhorn-system
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://gitea.192.168.40.200.nip.io/homelab/pi-k3s.git
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cert-manager
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: cert-manager
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://gitea.192.168.40.200.nip.io/homelab/pi-k3s.git
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitea
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: gitea
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://gitea.192.168.40.200.nip.io/homelab/pi-k3s.git
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: argocd
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://gitea.192.168.40.200.nip.io/homelab/pi-k3s.git
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vault
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: vault
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://gitea.192.168.40.200.nip.io/homelab/pi-k3s.git
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8tz
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: k8tz
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://gitea.192.168.40.200.nip.io/homelab/pi-k3s.git
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: home-assistant
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: home-assistant
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://gitea.192.168.40.200.nip.io/homelab/pi-k3s.git
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pi-hole
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: pi-hole
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://gitea.192.168.40.200.nip.io/homelab/pi-k3s.git
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dashboard
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: dashboard
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://gitea.192.168.40.200.nip.io/homelab/pi-k3s.git
