overseerr:
  image:
    repository: hotio/overseerr
    tag: release-1.30.1

  env:
    TZ: Europe/Madrid
    LOG_LEVEL: info

  ingress:
    main:
      enabled: true

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        # kubernetes.io/tls-acme: "true"

      ingressClassName: "nginx"

      hosts:
        - host: overseerr.local.tecno-fly.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: overseerr
                port: 5055
      tls:
       - secretName: overseerr-tls
         hosts:
           - overseerr.local.tecno-fly.com

  persistence:
    config:
      enabled: false
      storageClass: longhorn
      mountPath: /app/config