overseerr:
  # image:
  #   repository: ghcr.io/sct/overseerr
  #   tag: 1.33.2
  image:
    repository: ghcr.io/hotio/overseerr
    tag: release-1.33.2

  podOptions:
    hostUsers: false
    nodeSelector:
      kubernetes.io/arch: null

  TZ: Europe/Madrid

  service:
    main:
      ports:
        main:
          port: 5055
          targetPort: 5055

  ingress:
    main:
      enabled: true

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        # kubernetes.io/tls-acme: "true"
        hajimari.io/appName: Overseerr
        hajimari.io/icon: filmstrip
        hajimari.io/group: Downloads
        hajimari.io/targetBlank: 'false'

      ingressClassName: "nginx"

      hosts:
        - host: overseerr.local.tecno-fly.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: overseerr
                port: 5055
      tls:
        - secretName: overseerr-tls
          hosts:
            - overseerr.local.tecno-fly.com
      integrations:
        traefik:
          enabled: false

  persistence:
    config:
      enabled: true
      storageClass: longhorn
      size: 5Gi
      mountPath: "/app/config"

  securityContext:
    container:
      PUID: 1000
      PGID: 1000
      UMASK: "002"
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      readOnlyRootFilesystem: false
      allowPrivilegeEscalation: false
      privileged: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        add: []
        drop:
          - ALL
    pod:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: []
      sysctls: []