calibre:
  image:
    repository: linuxserver/calibre
    tag: v6.8.0-ls191

  env:
    TZ: Europe/Madrid
    GUAC_USER: <path:pi-k3s/data/apps/calibre#username>
    GUAC_PASS: <path:pi-k3s/data/apps/calibre#password>
    # CLI_ARGS:

  ingress:
    main:
      enabled: true

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        # kubernetes.io/tls-acme: "true"

      ingressClassName: "nginx"

      hosts:
        - host: calibre.local.tecno-fly.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: calibre
                port: 8080
      tls:
       - secretName: calibre-tls
         hosts:
           - calibre.local.tecno-fly.com

  persistence:
    config:
      enabled: true
      storageClass: longhorn

    media:
      enabled: true
      storageClass: nfs-media
      accessMode: ReadWriteOnce
      size: 6Ti
      mountPath: /media