---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-external-service
  namespace: external-endpoints
spec:
  ports:
  - name: http
    port: 30013
    protocol: TCP
    targetPort: 30013
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: jellyfin-external-service
  namespace: external-endpoints
subsets:
- addresses:
  - ip: 192.168.40.250
  ports:
  - name: http
    port: 30013
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    hajimari.io/appName: Jellyfin
    hajimari.io/icon: play-box
    hajimari.io/group: Media
    hajimari.io/targetBlank: 'false'
  name: jellyfin-external-ingress
  namespace: external-endpoints
spec:
  ingressClassName: nginx
  rules:
  - host: jellyfin.local.tecno-fly.com
    http:
      paths:
      - backend:
          service:
            name: jellyfin-external-service
            port:
              number: 30013
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - jellyfin.local.tecno-fly.com
    secretName: jellyfin-tls
