---
apiVersion: v1
kind: Service
metadata:
  name: minio-external-service
  namespace: external-endpoints
spec:
  ports:
  - name: http
    port: 9002
    protocol: TCP
    targetPort: 9002
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: minio-external-service
  namespace: external-endpoints
subsets:
- addresses:
  - ip: 192.168.40.250
  ports:
  - name: http
    port: 9002
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    hajimari.io/appName: MinIO
    hajimari.io/icon: bucket
    hajimari.io/group: NAS
    hajimari.io/targetBlank: 'false'
  name: minio-external-ingress
  namespace: external-endpoints
spec:
  ingressClassName: nginx
  rules:
  - host: minio.local.tecno-fly.com
    http:
      paths:
      - backend:
          service:
            name: minio-external-service
            port:
              number: 9002
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - minio.local.tecno-fly.com
    secretName: minio-tls
