---
apiVersion: v1
kind: Service
metadata:
  name: netdata-external-service
  namespace: external-endpoints
spec:
  ports:
  - name: http
    port: 20489
    protocol: TCP
    targetPort: 20489
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: netdata-external-service
  namespace: external-endpoints
subsets:
- addresses:
  - ip: 192.168.40.250
  ports:
  - name: http
    port: 20489
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    hajimari.io/appName: TrueNAS - NetData
    hajimari.io/icon: chart-bar
    hajimari.io/group: Monitoring
    hajimari.io/targetBlank: 'false'
  name: netdata-external-ingress
  namespace: external-endpoints
spec:
  ingressClassName: nginx
  rules:
  - host: netdata.local.tecno-fly.com
    http:
      paths:
      - backend:
          service:
            name: netdata-external-service
            port:
              number: 20489
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - netdata.local.tecno-fly.com
    secretName: netdata-tls
