---
apiVersion: v1
kind: Service
metadata:
  name: pi-hole-external-service
  namespace: external-endpoints
spec:
  ports:
  - name: http
    port: 9089
    protocol: TCP
    targetPort: 9089
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pi-hole-external-service
  namespace: external-endpoints
subsets:
- addresses:
  - ip: 192.168.40.250
  ports:
  - name: http
    port: 9089
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  name: pi-hole-external-ingress
  namespace: external-endpoints
spec:
  ingressClassName: nginx
  rules:
  - host: pi-hole-2.local.tecno-fly.com
    http:
      paths:
      - backend:
          service:
            name: pi-hole-external-service
            port:
              number: 9089
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - pi-hole-2.local.tecno-fly.com
    secretName: pi-hole-tls
