---
apiVersion: v1
kind: Service
metadata:
  name: pi-hole-0-service
  namespace: external-endpoints
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pi-hole-0-service
  namespace: external-endpoints
subsets:
- addresses:
  - ip: 192.168.40.254
  ports:
  - name: http
    port: 80
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    hajimari.io/appName: Pi-Hole-0
    hajimari.io/icon: dns-outline
    hajimari.io/group: Network
    hajimari.io/targetBlank: 'false'
  name: pi-hole-0-ingress
  namespace: external-endpoints
spec:
  ingressClassName: nginx
  rules:
  - host: pi-hole-0.local.tecno-fly.com
    http:
      paths:
      - backend:
          service:
            name: pi-hole-0-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - pi-hole-0.local.tecno-fly.com
    secretName: pi-hole-tls

