---
apiVersion: v1
kind: Service
metadata:
  name: plex-external-service
  namespace: external-endpoints
spec:
  ports:
  - name: http
    port: 32400
    protocol: TCP
    targetPort: 32400
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: plex-external-service
  namespace: external-endpoints
subsets:
- addresses:
  - ip: 192.168.40.250
  ports:
  - name: http
    port: 32400
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    hajimari.io/appName: Plex
    hajimari.io/icon: play-box
    hajimari.io/group: Media
    hajimari.io/targetBlank: 'false'
  name: plex-external-ingress
  namespace: external-endpoints
spec:
  ingressClassName: nginx
  rules:
  - host: plex.local.tecno-fly.com
    http:
      paths:
      - backend:
          service:
            name: plex-external-service
            port:
              number: 32400
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - plex.local.tecno-fly.com
    secretName: plex-tls
