---
apiVersion: v1
kind: Service
metadata:
  name: s3-external-service
  namespace: external-endpoints
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: s3-external-service
  namespace: external-endpoints
subsets:
- addresses:
  - ip: 192.168.40.250
  ports:
  - name: http
    port: 9000
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  name: s3-external-ingress
  namespace: external-endpoints
spec:
  ingressClassName: nginx
  rules:
  - host: s3.local.tecno-fly.com
    http:
      paths:
      - backend:
          service:
            name: s3-external-service
            port:
              number: 9000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - s3.local.tecno-fly.com
    secretName: s3-tls
