---
apiVersion: v1
kind: Service
metadata:
  name: truenas-external-service
  namespace: external-endpoints
spec:
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 443
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: truenas-external-service
  namespace: external-endpoints
subsets:
- addresses:
  - ip: 192.168.40.250
  ports:
  - name: http
    port: 443
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  name: truenas-external-ingress
  namespace: external-endpoints
spec:
  ingressClassName: nginx
  rules:
  - host: truenas.local.tecno-fly.com
    http:
      paths:
      - backend:
          service:
            name: truenas-external-service
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - truenas.local.tecno-fly.com
    secretName: truenas-tls
