---
apiVersion: v1
kind: Service
metadata:
  name: unifi-external-service
  namespace: external-endpoints
spec:
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 443
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: unifi-external-service
  namespace: external-endpoints
subsets:
- addresses:
  - ip: 192.168.0.1
  ports:
  - name: http
    port: 443
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  name: unifi-external-ingress
  namespace: external-endpoints
spec:
  ingressClassName: nginx
  rules:
  - host: unifi.local.tecno-fly.com
    http:
      paths:
      - backend:
          service:
            name: unifi-external-service
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - unifi.local.tecno-fly.com
    secretName: unifi-tls
