requestrr:
  image:
    repository: ghcr.io/hotio/requestrr
    tag: release-2.1.6

  podOptions:
    hostUsers: false
    nodeSelector:
      kubernetes.io/arch: null

  TZ: Europe/Madrid

  ingress:
    main:
      enabled: true

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        # kubernetes.io/tls-acme: "true"
        hajimari.io/appName: Requestrr
        hajimari.io/icon: filmstrip
        hajimari.io/group: Downloads
        hajimari.io/targetBlank: 'false'

      ingressClassName: "nginx"

      hosts:
        - host: requestrr.local.tecno-fly.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: requestrr
                port: 4545
      tls:
        - secretName: radarr-tls
          hosts:
            - requestrr.local.tecno-fly.com
      integrations:
        traefik:
          enabled: false

  persistence:
    config:
      enabled: true
      storageClass: longhorn
      size: 5Gi
      mountPath: "/root/config"
    varrun:
      enabled: true
