apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-secret
  namespace: gitea
type: Opaque
stringData:
  email: <path:pi-k3s/data/platform/gitea#email>
  password: <path:pi-k3s/data/platform/gitea#password>
  username: <path:pi-k3s/data/platform/gitea#username>
