lidarr:
  image:
    repository: ghcr.io/hotio/lidarr
    tag: release-2.5.3.4341

  env:
    TZ: Europe/Madrid

  ingress:
    main:
      enabled: true

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        # kubernetes.io/tls-acme: "true"
        hajimari.io/appName: Lidarr
        hajimari.io/icon: headphones
        hajimari.io/group: Downloads
        hajimari.io/targetBlank: 'false'

      ingressClassName: "nginx"

      hosts:
        - host: lidarr.local.tecno-fly.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: lidarr
                port: 8686
      tls:
       - secretName: lidarr-tls
         hosts:
           - lidarr.local.tecno-fly.com

  persistence:
    config:
      enabled: true
      storageClass: longhorn
      size: 5Gi

    downloads:
      enabled: true
      storageClass: nfs-downloads
      accessMode: ReadWriteOnce
      size: 2Ti
      mountPath: /downloads

    media:
      enabled: true
      storageClass: nfs-media
      accessMode: ReadWriteOnce
      size: 6Ti
      mountPath: /media

  metrics:
    # -- Enable and configure Exportarr sidecar and Prometheus serviceMonitor.
    # @default -- See values.yaml
    enabled: false
    serviceMonitor:
      interval: 3m
      scrapeTimeout: 1m
      labels: {}
    # -- Enable and configure Prometheus Rules for the chart under this key.
    # @default -- See values.yaml
    prometheusRule:
      enabled: false
      labels: {}
      # -- Configure additionial rules for the chart under this key.
      # @default -- See prometheusrules.yaml
      rules: []
        # - alert: LidarrDown
        #   annotations:
        #     description: Lidarr service is down.
        #     summary: Lidarr is down.
        #   expr: |
        #     lidarr_system_status == 0
        #   for: 5m
        #   labels:
        #     severity: critical
    exporter:
      image:
        # -- image repository
        repository: ghcr.io/onedr0p/exportarr
        # -- image tag
        tag: v1.0.0
        # -- image pull policy
        pullPolicy: IfNotPresent
      env:
        # -- metrics port
        port: 9792
        # -- Set to true to enable gathering of additional metrics (slow)
        additionalMetrics: false
        # -- Set to true to enable gathering unknown queue items
        unknownQueueItems: false