apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-prometheus-stack-kube-controller-manager
  namespace: monitoring-system
spec:
  selector:
    matchLabels:
      component: kube-controller-manager
  namespaceSelector:
    any: true