prowlarr:
  image:
    repository: hotio/prowlarr
    tag: release-1.5.2.3484

  env:
    TZ: Europe/Madrid

  ingress:
    main:
      enabled: true

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        # kubernetes.io/tls-acme: "true"
        hajimari.io/appName: Prowlarr
        hajimari.io/icon: format-list-bulleted-square
        hajimari.io/group: Downloads
        hajimari.io/targetBlank: 'false'

      ingressClassName: "nginx"

      hosts:
        - host: prowlarr.local.tecno-fly.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: prowlarr
                port: 9696
      tls:
       - secretName: prowlarr-tls
         hosts:
           - prowlarr.local.tecno-fly.com

  persistence:
    config:
      enabled: true
      storageClass: longhorn
      size: 10Gi