metallb:
  rbac:
    create: true

  controller:
    enabled: true

    nodeSelector:
      kubernetes.io/role: master

    tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        value: "true"
        effect: NoSchedule

  speaker:
    enabled: false

  crds:
    enabled: true
