namespace: monitoring-system

resources:
- ./resources/alertmanager-discord.yaml
- ./resources/all.yaml

patches:
  - path: ./patches/kube-prometheus-stack-kube-proxy-service-monitor.yaml
    target:
      kind: ServiceMonitor
      name: kube-prometheus-stack-kube-proxy
      namespace: monitoring-system
  - path: ./patches/kube-prometheus-stack-kube-controller-manager-service-monitor.yaml
    target:
      kind: ServiceMonitor
      name: kube-prometheus-stack-kube-controller-manager
      namespace: monitoring-system
  - path: ./patches/kube-prometheus-stack-kube-scheduler-service-monitor.yaml
    target:
      kind: ServiceMonitor
      name: kube-prometheus-stack-kube-scheduler
      namespace: monitoring-system
  # - path: ./patches/kube-prometheus-stack-kube-scheduler-svc.yaml
  #   target:
  #     kind: Service
  #     name: kube-prometheus-stack-kube-scheduler
  #     namespace: monitoring-system
  # - path: ./patches/kube-prometheus-stack-kube-controller-manager-svc.yaml
  #   target:
  #     kind: Service
  #     name: kube-prometheus-stack-kube-controller-manager
  #     namespace: monitoring-system

# - ./patches/kube-prometheus-stack-kube-proxy-service-monitor.yaml
# - ./patches/kube-prometheus-stack-kube-controller-manager-service-monitor.yaml
# - ./patches/kube-prometheus-stack-kube-scheduler-service-monitor.yaml



# - ./patches/crd-prometheuses.yaml


# - ./patches/kube-prometheus-stack-kube-scheduler-svc.yaml
# - ./patches/kube-prometheus-stack-kube-controller-manager-svc.yaml



# kubectl label svc kube-prometheus-stack-kube-controller-manager -n monitoring-system component=kube-controller-manager
# kubectl label svc kube-prometheus-stack-kube-scheduler -n monitoring-system component: component=kube-scheduler