---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-discord-webhook-configmap
  namespace: monitoring-system
data:
  DISCORD_WEBHOOK: <path:pi-k3s/data/system/monitoring-system/alertmanager#DISCORD_WEBHOOK>
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-discord
  namespace: monitoring-system
spec:
  selector:
    app: alertmanager-discord
  ports:
  - protocol: TCP
    port: 9094
    targetPort: 9094
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-discord
  namespace: monitoring-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-discord
  template:
    metadata:
      labels:
        app: alertmanager-discord
    spec:
      containers:
      - name: alertmanager-discord
        image: franjlytools/alertmanager-discord:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9094
          name: http
          protocol: TCP
        env:
        - name: DISCORD_WEBHOOK
          valueFrom:
            configMapKeyRef:
              key: DISCORD_WEBHOOK
              name: alertmanager-discord-webhook-configmap
      dnsPolicy: ClusterFirst
      restartPolicy: Always