apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-target-credential-secret
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: <path:pi-k3s/data/system/longhorn-system#access-key>
  AWS_SECRET_ACCESS_KEY: <path:pi-k3s/data/system/longhorn-system#secret-key>
  AWS_ENDPOINTS: https://<path:pi-k3s/data/system/minio#host>:<path:pi-k3s/data/system/minio#port>
  AWS_CERT: <path:pi-k3s/data/system/minio#ca-cert>
