---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: calico-metrics
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: calico-system
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/Franjly/homelab-pi-k3s.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico-metrics
  namespace: argocd
spec:
  destination:
    namespace: calico-system
    server: https://kubernetes.default.svc
  project: calico-metrics
  source:
    path: system/calico-metrics
    plugin:
      name: kustomized-helm
    repoURL: https://github.com/Franjly/homelab-pi-k3s.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
