---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring-system
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: monitoring-system
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/Franjly/homelab-pi-k3s.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi-poller
  namespace: argocd
spec:
  destination:
    namespace: monitoring-system
    server: https://kubernetes.default.svc
  project: monitoring-system
  source:
    path: system/unifi-poller
    plugin:
      name: vault-kustomized-helm
    repoURL: https://github.com/Franjly/homelab-pi-k3s.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  destination:
    namespace: monitoring-system
    server: https://kubernetes.default.svc
  project: monitoring-system
  source:
    path: system/uptime-kuma
    plugin:
      name: vault-kustomized-helm
    repoURL: https://github.com/Franjly/homelab-pi-k3s.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
